[project]
name = "p79-sample"
version = "0.1.0"
description = "Example project for the P79 course"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pynacl==1.5.0",
]

[dependency-groups]
dev = [
    "ty>=0.0.8",
]
